version: "3"

services:
  ops:
    container_name: ops
    build:
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    volumes:
      - /Users/sergio2/Desktop/django/operations:/app
    command: bash -c "pip install -r requirements.txt && cd operation && python manage.py runserver 0:80"
    tty: true