version: "3"

services:
  ops:
    container_name: ops
    build:
      dockerfile: ./Dockerfile
    ports:
      - 81:80
    volumes:
      - .:/app
    command: bash -c "pip install -r requirements.txt && cd operation && python manage.py runserver 0:80"
    tty: true